spring:
 datasource:
  url: jdbc:mysql://%s:3306/%s?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 
  driver-class-name: com.mysql.jdbc.Driver

logging:
 config: classpath:log4j2.xml